export interface Wilaya {
  code: number;
  name: string;
  arabicName: string;
}

export const ALGERIAN_WILAYAS: Wilaya[] = [
  { code: 1, name: "Adrar", arabicName: "أدرار" },
  { code: 2, name: "Chlef", arabicName: "الشلف" },
  { code: 3, name: "Laghouat", arabicName: "الأغواط" },
  { code: 4, name: "Oum El Bouaghi", arabicName: "أم البواقي" },
  { code: 5, name: "Batna", arabicName: "باتنة" },
  { code: 6, name: "Béjaïa", arabicName: "بجاية" },
  { code: 7, name: "Biskra", arabicName: "بسكرة" },
  { code: 8, name: "Béchar", arabicName: "بشار" },
  { code: 9, name: "Blida", arabicName: "البليدة" },
  { code: 10, name: "Bouira", arabicName: "البويرة" },
  { code: 11, name: "Tamanrasset", arabicName: "تمنراست" },
  { code: 12, name: "Tébessa", arabicName: "تبسة" },
  { code: 13, name: "Tlemcen", arabicName: "تلمسان" },
  { code: 14, name: "Tiaret", arabicName: "تيارت" },
  { code: 15, name: "Tizi Ouzou", arabicName: "تيزي وزو" },
  { code: 16, name: "Alger", arabicName: "الجزائر" },
  { code: 17, name: "Djelfa", arabicName: "الجلفة" },
  { code: 18, name: "Jijel", arabicName: "جيجل" },
  { code: 19, name: "Sétif", arabicName: "سطيف" },
  { code: 20, name: "Saïda", arabicName: "سعيدة" },
  { code: 21, name: "Skikda", arabicName: "سكيكدة" },
  { code: 22, name: "Sidi Bel Abbès", arabicName: "سيدي بلعباس" },
  { code: 23, name: "Annaba", arabicName: "عنابة" },
  { code: 24, name: "Guelma", arabicName: "قالمة" },
  { code: 25, name: "Constantine", arabicName: "قسنطينة" },
  { code: 26, name: "Médéa", arabicName: "المدية" },
  { code: 27, name: "Mostaganem", arabicName: "مستغانم" },
  { code: 28, name: "M'Sila", arabicName: "المسيلة" },
  { code: 29, name: "Mascara", arabicName: "معسكر" },
  { code: 30, name: "Ouargla", arabicName: "ورقلة" },
  { code: 31, name: "Oran", arabicName: "وهران" },
  { code: 32, name: "El Bayadh", arabicName: "البيض" },
  { code: 33, name: "Illizi", arabicName: "إليزي" },
  { code: 34, name: "Bordj Bou Arréridj", arabicName: "برج بوعريريج" },
  { code: 35, name: "Boumerdès", arabicName: "بومرداس" },
  { code: 36, name: "El Tarf", arabicName: "الطارف" },
  { code: 37, name: "Tindouf", arabicName: "تندوف" },
  { code: 38, name: "Tissemsilt", arabicName: "تيسمسيلت" },
  { code: 39, name: "El Oued", arabicName: "الوادي" },
  { code: 40, name: "Khenchela", arabicName: "خنشلة" },
  { code: 41, name: "Souk Ahras", arabicName: "سوق أهراس" },
  { code: 42, name: "Tipaza", arabicName: "تيبازة" },
  { code: 43, name: "Mila", arabicName: "ميلة" },
  { code: 44, name: "Aïn Defla", arabicName: "عين الدفلى" },
  { code: 45, name: "Naâma", arabicName: "النعامة" },
  { code: 46, name: "Aïn Témouchent", arabicName: "عين تموشنت" },
  { code: 47, name: "Ghardaïa", arabicName: "غرداية" },
  { code: 48, name: "Relizane", arabicName: "غليزان" },
  { code: 49, name: "El M'Ghair", arabicName: "المغير" },
  { code: 50, name: "El Meniaa", arabicName: "المنيعة" },
  { code: 51, name: "Ouled Djellal", arabicName: "أولاد جلال" },
  { code: 52, name: "Bordj Baji Mokhtar", arabicName: "برج باجي مختار" },
  { code: 53, name: "Béni Abbès", arabicName: "بني عباس" },
  { code: 54, name: "Timimoun", arabicName: "تيميمون" },
  { code: 55, name: "Touggourt", arabicName: "تقرت" },
  { code: 56, name: "Djanet", arabicName: "جانت" },
  { code: 57, name: "In Salah", arabicName: "عين صالح" },
  { code: 58, name: "In Guezzam", arabicName: "عين قزام" },
];

export const BLOOD_TYPES = ["A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-"] as const;
