services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vitalbook-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      APP_NAME: VitalBook
      APP_ENV: local
      APP_DEBUG: "true"
      APP_KEY: "base64:HrB/et5Yh+1paB4NOVNQTjpj5H2rRLxjS+gPCOYhT6A="
      APP_URL: "http://localhost:8000"
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: vitalbook
      DB_USERNAME: vitalbook_user
      DB_PASSWORD: vitalbook_secret_password
      REDIS_HOST: redis
      REDIS_PORT: 6379
      CACHE_STORE: redis
      QUEUE_CONNECTION: redis
      SESSION_DRIVER: redis
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - vitalbook-network

  postgres:
    image: postgres:18-alpine
    container_name: vitalbook-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: vitalbook
      POSTGRES_USER: vitalbook_user
      POSTGRES_PASSWORD: vitalbook_secret_password
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vitalbook_user -d vitalbook"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - vitalbook-network

  redis:
    image: redis:alpine
    container_name: vitalbook-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - vitalbook-network

volumes:
  pgdata:
  redisdata:

networks:
  vitalbook-network:
    driver: bridge
